# Local preset to build arm64 only toolchain (no x86_64 cross-compile)
[preset: local_buildbot_osx_package,no_test,macos_only]
mixin-preset=buildbot_osx_package,no_test,macos_only

# Explicitly disable cross-compile inference and clear cross-compile hosts
infer-cross-compile-hosts-on-darwin=0
cross-compile-hosts=
